# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

# Below is for apigee-istio

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

# Below is for adapter

[[constraint]]
  name = "istio.io/istio"
  branch = "release-1.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  branch = "master"

[[override]]
  name = "github.com/lestrrat-go/jwx"
  revision = "master"

# only used in tests
[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "~3.2.0"
