# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "github.com/gogo/protobuf/proto",
  "github.com/gogo/protobuf/jsonpb",
  "github.com/gogo/protobuf/protoc-gen-gogoslick",
  "github.com/gogo/protobuf/gogoproto",
  "github.com/lestrrat/go-jwx",
  "github.com/lestrrat/go-pdebug",
  "github.com/dgrijalva/jwt-go",
]

[[constraint]]
  name = "istio.io/api"
  revision = "a11fc3a78b68ede57ad46fb4d1f7fe5742325489"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "=0.5"

